"""Initial schema

Revision ID: f120bcef3846
Revises: 
Create Date: 2026-09-06 00:36:51.751220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.files.orm
import src.leads.orm
import src.quarantine.orm
import src.sales.orm

# revision identifiers, used by Alembic.
revision: str = 'f120bcef3846'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_identifier', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_customers_customer_identifier'), 'dim_customers', ['customer_identifier'], unique=True)
    op.create_index(op.f('ix_dim_customers_id'), 'dim_customers', ['id'], unique=False)
    op.create_table('dim_dates',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.CheckConstraint('day >= 1 AND day <= 31', name='check_valid_day'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='check_valid_month'),
    sa.CheckConstraint('quarter >= 1 AND quarter <= 4', name='check_valid_quarter'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_dates_full_date'), 'dim_dates', ['full_date'], unique=True)
    op.create_index(op.f('ix_dim_dates_id'), 'dim_dates', ['id'], unique=False)
    op.create_table('dim_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_products_category'), 'dim_products', ['category'], unique=False)
    op.create_index(op.f('ix_dim_products_id'), 'dim_products', ['id'], unique=False)
    op.create_index(op.f('ix_dim_products_sku'), 'dim_products', ['sku'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('hashed_file', sa.String(), nullable=True),
    sa.Column('assumed_type', sa.String(), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('potential_types', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'AUDITING', 'RETRYING', 'VALIDATING', 'PERSISTING', 'FINISHING', 'PROCESSED_CLEAN', 'PROCESSED_W_QUARANTINE', 'FAILURE_SCHEMA', 'REJECTED', 'SYSTEM_FAULT', name='filestatus'), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_processed_rows', sa.Integer(), nullable=False),
    sa.Column('quarantined_rows', sa.Integer(), nullable=False),
    sa.Column('expected_batches', src.files.orm.JSONSet(), nullable=False),
    sa.Column('validated_batches', src.files.orm.JSONSet(), nullable=False),
    sa.Column('completed_batches', src.files.orm.JSONSet(), nullable=False),
    sa.Column('processing_begun', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_finished', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempted_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_index(op.f('ix_files_hashed_file'), 'files', ['hashed_file'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_is_ambiguous'), 'files', ['is_ambiguous'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_table('lead_alerts_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_index(op.f('ix_lead_alerts_team_id'), 'lead_alerts_team', ['id'], unique=False)
    op.create_table('fact_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('revenue_amount', sa.Float(), nullable=False),
    sa.Column('sale_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customers.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_products.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_sales_customer_id'), 'fact_sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_date_id'), 'fact_sales', ['date_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_id'), 'fact_sales', ['id'], unique=False)
    op.create_index(op.f('ix_fact_sales_product_id'), 'fact_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_revenue_amount'), 'fact_sales', ['revenue_amount'], unique=False)
    op.create_index(op.f('ix_fact_sales_source_file_id'), 'fact_sales', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_transaction_id'), 'fact_sales', ['transaction_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'MQL', 'CONTACTED', 'QUALIFIED', 'REJECTED', name='leadstatus'), nullable=False),
    sa.Column('incoming_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_source_file_id'), 'leads', ['source_file_id'], unique=False)
    op.create_table('quarantined_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('assumed_type', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_hash')
    )
    op.create_index(op.f('ix_quarantined_rows_assumed_type'), 'quarantined_rows', ['assumed_type'], unique=False)
    op.create_index(op.f('ix_quarantined_rows_file_id'), 'quarantined_rows', ['file_id'], unique=False)
    op.create_index(op.f('ix_quarantined_rows_id'), 'quarantined_rows', ['id'], unique=False)
    op.create_table('lead_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.Column('alert_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_index(op.f('ix_lead_alerts_id'), 'lead_alerts', ['id'], unique=False)
    op.create_table('lead_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('incoming_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('custos_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_updates_id'), 'lead_updates', ['id'], unique=False)
    op.create_index(op.f('ix_lead_updates_source_file_id'), 'lead_updates', ['source_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_updates_source_file_id'), table_name='lead_updates')
    op.drop_index(op.f('ix_lead_updates_id'), table_name='lead_updates')
    op.drop_table('lead_updates')
    op.drop_index(op.f('ix_lead_alerts_id'), table_name='lead_alerts')
    op.drop_table('lead_alerts')
    op.drop_index(op.f('ix_quarantined_rows_id'), table_name='quarantined_rows')
    op.drop_index(op.f('ix_quarantined_rows_file_id'), table_name='quarantined_rows')
    op.drop_index(op.f('ix_quarantined_rows_assumed_type'), table_name='quarantined_rows')
    op.drop_table('quarantined_rows')
    op.drop_index(op.f('ix_leads_source_file_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_fact_sales_transaction_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_source_file_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_revenue_amount'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_product_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_date_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_customer_id'), table_name='fact_sales')
    op.drop_table('fact_sales')
    op.drop_index(op.f('ix_lead_alerts_team_id'), table_name='lead_alerts_team')
    op.drop_table('lead_alerts_team')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_is_ambiguous'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_hashed_file'), table_name='files')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_dim_products_sku'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_id'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_category'), table_name='dim_products')
    op.drop_table('dim_products')
    op.drop_index(op.f('ix_dim_dates_id'), table_name='dim_dates')
    op.drop_index(op.f('ix_dim_dates_full_date'), table_name='dim_dates')
    op.drop_table('dim_dates')
    op.drop_index(op.f('ix_dim_customers_id'), table_name='dim_customers')
    op.drop_index(op.f('ix_dim_customers_customer_identifier'), table_name='dim_customers')
    op.drop_table('dim_customers')
    # ### end Alembic commands ###
